### ISSUE TITLE
crash when i click on a player

### ISSUE THREAD

**Issue by bibihool** [Rjlintkh/bdsx-web-panel#3]
Error: This object is decayed. Native objects are unusable after it deleted
   at Anonymous function (C:\Users\hool\Desktop\server\bdsx\plugins\web-panel\src\server\socket.ts:92:17)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at Anonymous function (C:\Users\hool\Desktop\server\bdsx\node_modules\socket.io\lib\socket.js:527:7)
Exited with code 1
Re-Launch BDSX
3
2
1

**Comment by Rjlintkh** [comment]
I think this was a problem of bdsx at that time right? Regardless, thanks for ur report

**Comment by bibihool** [comment]
i think this bug happen again at 1.18.11 update
